name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]  # 修改为 master
  pull_request:
    branches: [ master ]  # 修改为 master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: next-app/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: ./next-app

    - name: Build static site
      run: npm run build
      working-directory: ./next-app

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'  # 修改为 master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./next-app/out